### ISSUE TITLE
pyinstaller issues

### ISSUE THREAD

**Issue by SantiSarGon** [alqasemy2020/pyzkfp#7]
Hello! I hope you are doing great. I write to you through this issue to know if you have used your library alongside pyinstaller?
I have my source code running without issues but I need to make it distributable. Pyinstaller has been my goto for some time but I cant make it work with pyzkfp.
When I run the exe file I get the issue System.IO.FileNotFoundException. File or assembly could not be loaded 'libzkfpcsharp'...
![Captura de pantalla 2024-03-28 115125](https://github.com/alqasemy2020/pyzkfp/assets/53830596/629b15fc-e46b-4747-bcaa-2ca5385cb624)

**Comment by aqasemi** [comment]
This is happening because you have to import data (dll file) from the lib's directory and pass it to the pyinstaller build command. 

Sol 1:
Create a .spec file and import the path of the data files.
For more information see [this](https://stackoverflow.com/a/48068640/20277745).

Sol 2:
install the library to your workflow and pass the `--add-data` arg to your build command.
Ex: `--add-data "src/pyzkfp_lib/dll/libzkfpcsharp.dll:."`
